repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: fix-encoding-pragma
        args: ['--remove']

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
        args: ['--config', '.black', '-v']

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-implicit-str-concat
          - flake8-comprehensions
          - flake8-simplify

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
      # args: [--no-strict-optional, --ignore-missing-imports]
      # additional_dependencies: [tokenize-rt==3.2.0]

  - repo: local
    hooks:
      - id: version-update
        name: version-update
        description: Update project version
        entry: bash .version-update.hook
        language: system
